variable "resource_name_prefix" {
  type        = string
  description = "Prefix to be prepended to all resource names. Will be autogenerated if null."
  default     = null

  validation {
    condition     = var.resource_name_prefix == null || can(regex("^([a-z][a-z0-9-_]*)?$", var.resource_name_prefix))
    error_message = "Invalid resource name prefix."
  }
}

variable "cache_dir" {
  type        = string
  description = "The directory in which to place files. Will be autogenerated based on the resource name prefix if omitted."
  default     = null

  # The validation doesn't work?

  # validation {
  #   condition     = var.cache_dir == null || length(var.cache_dir) != 0
  #   error_message = "The cache directory may not be empty."
  # }
}
