variable "resource_name_prefix" {
  type        = string
  description = "Prefix to be prepended to all resource names. Will be autogenerated if null."
  default     = null

  validation {
    condition     = var.resource_name_prefix == null || can(regex("^([a-z][a-z0-9-_]*)?$", var.resource_name_prefix))
    error_message = "Invalid resource name prefix."
  }
}

variable "cache_dir" {
  type        = string
  description = <<-EOD
    The directory in which to place local files. Will be autogenerated
    based on the resource name prefix if omitted.
  EOD
  default     = null

  # The validation doesn't work?

  # validation {
  #   condition     = var.cache_dir == null || length(var.cache_dir) != 0
  #   error_message = "The cache directory may not be empty."
  # }
}

variable "os" {
  type        = string
  description = "The underlying OS for the to-be-provisioned cluster."
}

variable "k0sctl_binary" {
  type        = string
  description = "Path to the k0sctl binary to use for local-exec provisioning."
  default     = "k0sctl"
  nullable    = false

  validation {
    condition     = length(var.k0sctl_binary) != 0
    error_message = "Path to the k0sctl binary may not be empty."
  }
}
