// SPDX-FileCopyrightText: k0s authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package applyconfigurations

import (
	v1beta1 "github.com/k0sproject/k0s/pkg/apis/etcd/v1beta1"
	etcdv1beta1 "github.com/k0sproject/k0s/pkg/client/applyconfigurations/etcd/v1beta1"
	internal "github.com/k0sproject/k0s/pkg/client/applyconfigurations/internal"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=etcd.k0sproject.io, Version=v1beta1
	case v1beta1.SchemeGroupVersion.WithKind("EtcdMember"):
		return &etcdv1beta1.EtcdMemberApplyConfiguration{}
	case v1beta1.SchemeGroupVersion.WithKind("EtcdMemberSpec"):
		return &etcdv1beta1.EtcdMemberSpecApplyConfiguration{}
	case v1beta1.SchemeGroupVersion.WithKind("JoinCondition"):
		return &etcdv1beta1.JoinConditionApplyConfiguration{}
	case v1beta1.SchemeGroupVersion.WithKind("Status"):
		return &etcdv1beta1.StatusApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
