// SPDX-FileCopyrightText: k0s authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// EtcdMemberSpecApplyConfiguration represents a declarative configuration of the EtcdMemberSpec type for use
// with apply.
type EtcdMemberSpecApplyConfiguration struct {
	Leave *bool `json:"leave,omitempty"`
}

// EtcdMemberSpecApplyConfiguration constructs a declarative configuration of the EtcdMemberSpec type for use with
// apply.
func EtcdMemberSpec() *EtcdMemberSpecApplyConfiguration {
	return &EtcdMemberSpecApplyConfiguration{}
}

// WithLeave sets the Leave field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Leave field is set to the value of the last call.
func (b *EtcdMemberSpecApplyConfiguration) WithLeave(value bool) *EtcdMemberSpecApplyConfiguration {
	b.Leave = &value
	return b
}
