// SPDX-FileCopyrightText: k0s authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	etcdv1beta1 "github.com/k0sproject/k0s/pkg/apis/etcd/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// JoinConditionApplyConfiguration represents a declarative configuration of the JoinCondition type for use
// with apply.
type JoinConditionApplyConfiguration struct {
	Type               *etcdv1beta1.ConditionType   `json:"type,omitempty"`
	Status             *etcdv1beta1.ConditionStatus `json:"status,omitempty"`
	LastTransitionTime *v1.Time                     `json:"lastTransitionTime,omitempty"`
	Message            *string                      `json:"message,omitempty"`
}

// JoinConditionApplyConfiguration constructs a declarative configuration of the JoinCondition type for use with
// apply.
func JoinCondition() *JoinConditionApplyConfiguration {
	return &JoinConditionApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *JoinConditionApplyConfiguration) WithType(value etcdv1beta1.ConditionType) *JoinConditionApplyConfiguration {
	b.Type = &value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *JoinConditionApplyConfiguration) WithStatus(value etcdv1beta1.ConditionStatus) *JoinConditionApplyConfiguration {
	b.Status = &value
	return b
}

// WithLastTransitionTime sets the LastTransitionTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastTransitionTime field is set to the value of the last call.
func (b *JoinConditionApplyConfiguration) WithLastTransitionTime(value v1.Time) *JoinConditionApplyConfiguration {
	b.LastTransitionTime = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *JoinConditionApplyConfiguration) WithMessage(value string) *JoinConditionApplyConfiguration {
	b.Message = &value
	return b
}
