// SPDX-FileCopyrightText: k0s authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// StatusApplyConfiguration represents a declarative configuration of the Status type for use
// with apply.
type StatusApplyConfiguration struct {
	PeerAddress     *string                           `json:"peerAddress,omitempty"`
	MemberID        *string                           `json:"memberID,omitempty"`
	ReconcileStatus *string                           `json:"reconcileStatus,omitempty"`
	Message         *string                           `json:"message,omitempty"`
	Conditions      []JoinConditionApplyConfiguration `json:"conditions,omitempty"`
}

// StatusApplyConfiguration constructs a declarative configuration of the Status type for use with
// apply.
func Status() *StatusApplyConfiguration {
	return &StatusApplyConfiguration{}
}

// WithPeerAddress sets the PeerAddress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PeerAddress field is set to the value of the last call.
func (b *StatusApplyConfiguration) WithPeerAddress(value string) *StatusApplyConfiguration {
	b.PeerAddress = &value
	return b
}

// WithMemberID sets the MemberID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MemberID field is set to the value of the last call.
func (b *StatusApplyConfiguration) WithMemberID(value string) *StatusApplyConfiguration {
	b.MemberID = &value
	return b
}

// WithReconcileStatus sets the ReconcileStatus field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReconcileStatus field is set to the value of the last call.
func (b *StatusApplyConfiguration) WithReconcileStatus(value string) *StatusApplyConfiguration {
	b.ReconcileStatus = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *StatusApplyConfiguration) WithMessage(value string) *StatusApplyConfiguration {
	b.Message = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *StatusApplyConfiguration) WithConditions(values ...*JoinConditionApplyConfiguration) *StatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
