# options for analysis running
run:
  timeout: 8m

  skip-dirs-use-default: false
  skip-dirs:
    - build
    - pkg/helm
    - static
    - hack
    - embedded-bins
    - pkg/apis/k0s.k0sproject.io/clientset
  skip-files:
    - "zz_*"
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  enable:
    - revive
    - gofmt
    - goheader

linters-settings:
  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: false
  golint:
    min-confidence: 0
  goheader:
    template-path: .go-header.txt
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - source: "^//go:build"
      linters:
        - goheader

severity:
  default-severity: error
  rules:
    # Deprecations should be warnings, not hard errors.
    # Note that this doesn't change the exit code of the CLI.
    # (https://github.com/golangci/golangci-lint/issues/708#issuecomment-840916783)
    - linters: [staticcheck]
      text: "^SA1019:"
      severity: warn
