/*
Copyright k0s authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/k0sproject/k0s/pkg/apis/k0s/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSupportBundleRequests implements SupportBundleRequestInterface
type FakeSupportBundleRequests struct {
	Fake *FakeK0sV1beta1
}

var supportbundlerequestsResource = schema.GroupVersionResource{Group: "k0s.k0sproject.io", Version: "v1beta1", Resource: "supportbundlerequests"}

var supportbundlerequestsKind = schema.GroupVersionKind{Group: "k0s.k0sproject.io", Version: "v1beta1", Kind: "SupportBundleRequest"}

// Get takes name of the supportBundleRequest, and returns the corresponding supportBundleRequest object, and an error if there is any.
func (c *FakeSupportBundleRequests) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.SupportBundleRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(supportbundlerequestsResource, name), &v1beta1.SupportBundleRequest{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.SupportBundleRequest), err
}

// List takes label and field selectors, and returns the list of SupportBundleRequests that match those selectors.
func (c *FakeSupportBundleRequests) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.SupportBundleRequestList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(supportbundlerequestsResource, supportbundlerequestsKind, opts), &v1beta1.SupportBundleRequestList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.SupportBundleRequestList{ListMeta: obj.(*v1beta1.SupportBundleRequestList).ListMeta}
	for _, item := range obj.(*v1beta1.SupportBundleRequestList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested supportBundleRequests.
func (c *FakeSupportBundleRequests) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(supportbundlerequestsResource, opts))
}

// Create takes the representation of a supportBundleRequest and creates it.  Returns the server's representation of the supportBundleRequest, and an error, if there is any.
func (c *FakeSupportBundleRequests) Create(ctx context.Context, supportBundleRequest *v1beta1.SupportBundleRequest, opts v1.CreateOptions) (result *v1beta1.SupportBundleRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(supportbundlerequestsResource, supportBundleRequest), &v1beta1.SupportBundleRequest{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.SupportBundleRequest), err
}

// Update takes the representation of a supportBundleRequest and updates it. Returns the server's representation of the supportBundleRequest, and an error, if there is any.
func (c *FakeSupportBundleRequests) Update(ctx context.Context, supportBundleRequest *v1beta1.SupportBundleRequest, opts v1.UpdateOptions) (result *v1beta1.SupportBundleRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(supportbundlerequestsResource, supportBundleRequest), &v1beta1.SupportBundleRequest{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.SupportBundleRequest), err
}

// Delete takes name of the supportBundleRequest and deletes it. Returns an error if one occurs.
func (c *FakeSupportBundleRequests) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(supportbundlerequestsResource, name, opts), &v1beta1.SupportBundleRequest{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSupportBundleRequests) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(supportbundlerequestsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.SupportBundleRequestList{})
	return err
}

// Patch applies the patch and returns the patched supportBundleRequest.
func (c *FakeSupportBundleRequests) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.SupportBundleRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(supportbundlerequestsResource, name, pt, data, subresources...), &v1beta1.SupportBundleRequest{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.SupportBundleRequest), err
}
