/*
Copyright k0s authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1beta1 "github.com/k0sproject/k0s/pkg/apis/k0s/v1beta1"
	scheme "github.com/k0sproject/k0s/pkg/client/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SupportBundleRequestsGetter has a method to return a SupportBundleRequestInterface.
// A group's client should implement this interface.
type SupportBundleRequestsGetter interface {
	SupportBundleRequests() SupportBundleRequestInterface
}

// SupportBundleRequestInterface has methods to work with SupportBundleRequest resources.
type SupportBundleRequestInterface interface {
	Create(ctx context.Context, supportBundleRequest *v1beta1.SupportBundleRequest, opts v1.CreateOptions) (*v1beta1.SupportBundleRequest, error)
	Update(ctx context.Context, supportBundleRequest *v1beta1.SupportBundleRequest, opts v1.UpdateOptions) (*v1beta1.SupportBundleRequest, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.SupportBundleRequest, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.SupportBundleRequestList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.SupportBundleRequest, err error)
	SupportBundleRequestExpansion
}

// supportBundleRequests implements SupportBundleRequestInterface
type supportBundleRequests struct {
	client rest.Interface
}

// newSupportBundleRequests returns a SupportBundleRequests
func newSupportBundleRequests(c *K0sV1beta1Client) *supportBundleRequests {
	return &supportBundleRequests{
		client: c.RESTClient(),
	}
}

// Get takes name of the supportBundleRequest, and returns the corresponding supportBundleRequest object, and an error if there is any.
func (c *supportBundleRequests) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.SupportBundleRequest, err error) {
	result = &v1beta1.SupportBundleRequest{}
	err = c.client.Get().
		Resource("supportbundlerequests").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SupportBundleRequests that match those selectors.
func (c *supportBundleRequests) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.SupportBundleRequestList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.SupportBundleRequestList{}
	err = c.client.Get().
		Resource("supportbundlerequests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested supportBundleRequests.
func (c *supportBundleRequests) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("supportbundlerequests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a supportBundleRequest and creates it.  Returns the server's representation of the supportBundleRequest, and an error, if there is any.
func (c *supportBundleRequests) Create(ctx context.Context, supportBundleRequest *v1beta1.SupportBundleRequest, opts v1.CreateOptions) (result *v1beta1.SupportBundleRequest, err error) {
	result = &v1beta1.SupportBundleRequest{}
	err = c.client.Post().
		Resource("supportbundlerequests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(supportBundleRequest).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a supportBundleRequest and updates it. Returns the server's representation of the supportBundleRequest, and an error, if there is any.
func (c *supportBundleRequests) Update(ctx context.Context, supportBundleRequest *v1beta1.SupportBundleRequest, opts v1.UpdateOptions) (result *v1beta1.SupportBundleRequest, err error) {
	result = &v1beta1.SupportBundleRequest{}
	err = c.client.Put().
		Resource("supportbundlerequests").
		Name(supportBundleRequest.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(supportBundleRequest).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the supportBundleRequest and deletes it. Returns an error if one occurs.
func (c *supportBundleRequests) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("supportbundlerequests").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *supportBundleRequests) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("supportbundlerequests").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched supportBundleRequest.
func (c *supportBundleRequests) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.SupportBundleRequest, err error) {
	result = &v1beta1.SupportBundleRequest{}
	err = c.client.Patch(pt).
		Resource("supportbundlerequests").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
