---
apiVersion: v1
kind: ConfigMap
metadata:
  name: calico-windows-config
  namespace: kube-system
data:
  # Valid values for Calico networking are: "vxlan", "windows-bgp"
  # For non-C alico networking, the only value is "none".
  CALICO_NETWORKING_BACKEND: "vxlan" #"{{ .Mode }}"
  # The Kubernetes API server host and port. This is required to
  # bootstrap Calico for Windows.
  KUBERNETES_SERVICE_HOST: "16.170.173.94"
  KUBERNETES_SERVICE_PORT: "6443"
  # The Kubernetes service clusterIP range configured in your cluster.
  # This must match the service-cluster-ip-range used by kube-apiserver.
  # from microk8s
  K8S_SERVICE_CIDR: "10.96.0.0/12"
  # The DNS nameservers that will be used in the CNI configuration.
  DNS_NAME_SERVERS: "10.96.0.10"
  # The CNI bin dir. This must match the containerd configuration on the Windows nodes.
  CNI_BIN_DIR:  "c:\\opt\\cni\\bin" # "{{ .CNIBin }}"
  # The CNI conf dir. This must match the containerd configuration on the Windows nodes.
  CNI_CONF_DIR: "c:\\etc\\cni\\net.d" # "{{ .CNIConf }}" # 
  # Felix health must be enabled.
  FELIX_HEALTHENABLED: "true"