name: Check OS tests

on:
  push:

env:
  TERRAFORM_VERSION: 1.4.6

jobs:
  verify_tf:
    strategy:
      fail-fast: false
      matrix:
        backend:
          - aws
          - libvirt

    name: "${{ matrix.backend }} :: Terraform :: Validate"
    runs-on: ubuntu-22.04

    defaults:
      run:
        working-directory: hack/ostests/backends/${{ matrix.backend }}

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false

      - run: terraform fmt -check
      - run: terraform init
      - run: terraform validate -no-color
