name: Cleaner

on:
  push:
    branches:
      - cleaner-test

# Reference: https://github.com/actions/runner-images/blob/ubuntu22/20231001.1/images/linux/Ubuntu2204-Readme.md

jobs:
  cleaner:
    name: Cleaner
    runs-on: ubuntu-22.04

    steps:
      - name: Cleaner
        run: |
          set +eux
          df -h /
          docker system prune --all --force &
          sudo rm -rf /imagegeneration/installers &
          sudo rm -rf -- "${ANDROID_SDK_ROOT-/opt/nevermind}" &
          wait
          df -h /

      # - name: Files
      #   run: sudo find / -type f -mount > files || true

      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: files
      #     path: files
