# OS testing matrix. See ../../hack/ostests/README.md for details.

name: "OS tests :: Dispatch"

on:
  workflow_dispatch:
    inputs:
      e2e-parallel:
        type: boolean
        description: Whether to run tests in parallel.
        default: true
      e2e-focus:
        type: string
        description: The selector for the e2e tests to be run.
        default: \[Conformance\]
      oses:
        type: string
        description: The operating systems to test.
        required: true
        default: >-
          [
            "alpine_3_17",
            "centos_7", "centos_8", "centos_9",
            "debian_10", "debian_11",
            "fcos_38",
            "fedora_38",
            "flatcar",
            "oracle_7_9", "oracle_8_7", "oracle_9_1",
            "rhel_7", "rhel_8", "rhel_9",
            "rocky_8", "rocky_9",
            "ubuntu_2004", "ubuntu_2204", "ubuntu_2304"
          ]
      network-providers:
        type: string
        description: The k0s network providers to test.
        required: true
        default: >-
          [
            "kuberouter",
            "calico"
          ]

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build-k0s.yml
    with: { target-os: linux, target-arch: amd64 }

  e2e-matrix:
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(github.event.inputs.oses) }}
        network-provider: ${{ fromJSON(github.event.inputs.network-providers) }}

    name: "e2e matrix :: ${{ matrix.os }} :: ${{ matrix.network-provider }}"
    needs: build
    uses: ./.github/workflows/ostests-e2e.yaml
    with:
      e2e-parallel: ${{ github.event.inputs.e2e-parallel }}
      e2e-focus: ${{ github.event.inputs.e2e-focus }}
      os: ${{ matrix.os }}
      network-provider: ${{ matrix.network-provider }}
