name: OS tests

on:
  # push:
  workflow_dispatch:
    inputs:
      oses:
        description: The Operating Systems to test.
        default: >-
          {
            "alpine_317",
            "ubuntu_2204"
          }

env:
  TERRAFORM_VERSION: 1.4.6
  K0SCTL_VERSION: 0.15.1
  AWS_REGION: us-east-1

jobs:
  # terraform:
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       backend:
  #         - aws
  #         - libvirt

  #   name: "OS tests :: terraform :: ${{ matrix.backend }}"
  #   runs-on: ubuntu-22.04

  #   defaults:
  #     run:
  #       working-directory: hack/ostests/backends/${{ matrix.backend }}

  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         persist-credentials: false

  #     - uses: hashicorp/setup-terraform@v2
  #       with:
  #         terraform_version: ${{ env.TERRAFORM_VERSION }}
  #         terraform_wrapper: false

  #     - run: terraform fmt -check
  #     - run: terraform init
  #     - run: terraform validate -no-color

  build:
    name: Build
    uses: ./.github/workflows/build-k0s-amd64.yml
    with:
      target: linux

  network-conformance:
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(github.event.inputs.oses) }}

    name: "NetConf :: AWS :: ${{ matrix.os }}"
    runs-on: ubuntu-22.04
    needs: build

    env:
      TF_VAR_os_resource_name_prefix: gha-${{ github.run_id }}-${{ github.run_attempt }}"
      TF_VAR_os: ${{ matrix.os }}
      TF_VAR_cache_dir: ${{ github.workspace }}/.cache/k0s-ostests

    defaults:
      run:
        working-directory: hack/ostests/backends/aws

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: "Cache :: k0s"
        uses: actions/cache@v3
        id: cache-compiled-executable
        with:
          key: ${{ needs.build.outputs.cache-key }}
          path: |
            k0s
            k0s.exe
            airgap-images.txt
            airgap-image-bundle-cache-key.txt

      - name: "Terraform :: Requisites"
        env:
          OSTESTS_OS: ${{ matrix.os }}
          OSTESTS_CACHE_HIT: ${{ steps.cache-compiled-executable.outputs.cache-hit }}
        run: |
          jq --version

          k0sExecutablePath="$(pwd)/k0sctl"
          k0sctlExecutablePath="$(pwd)/k0sctl"

          if [ "$OSTESTS_CACHE_HIT" != true ] || ! [ -f "$k0sExecutablePath" ] ; then
            echo Failed to restore cached k0s executable! 1>&2
            exit 1
          fi

          curl -sSLo "$k0sctlExecutablePath" "https://github.com/k0sproject/k0sctl/releases/download/v${K0SCTL_VERSION}/k0sctl-linux-x64"
          chmod +x -- "$k0sctlExecutablePath"
          "$k0sctlExecutablePath" version

          {
            echo "TF_VAR_k0s_executable_path=$k0sExecutablePath"
            echo "TF_VAR_k0sctl_executable_path=$k0sctlExecutablePath"
          } >> "$GITHUB_ENV"

      - name: "Terraform :: Setup"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false

      - name: "Terraform :: Init"
        id: tf-init
        run: terraform init

      - name: "Terraform :: Apply"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        run: |
          terraform apply -auto-approve

          kubeconfigPath="$(pwd)/kubeconfig"
          terraform output -raw k0s_kubeconfig > "$kubeconfigPath"
          echo "KUBECONFIG=$kubeconfigPath" >> "$GITHUB_ENV"

      - name: "Network conformance tests :: Run"
        working-directory: inttest
        run: make check-network
        continue-on-error: true

      - name: "Network conformance tests :: Retrieve"
        working-directory: inttest
        run: make get-conformance-results

      - name: "Network conformance tests :: Upload"
        uses: actions/upload-artifact@v3
        with:
          name: network-conformance-results-${{ matrix.os }}
          path: inttest/*_sonobuoy_*.tar.gz

      - name: "Terraform :: Destroy"
        if: always() && steps.tf-init.conclusion == 'success'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        run: terraform destroy -auto-approve
