name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - tmp/rebuild-docs
  release:
    types:
      - published

env:
  GO_VERSION: ~1.17
  NODE_VERSION: 12.x
  PYTHON_VERSION: 3.x

jobs:
  build:
    strategy:
      max-parallel: 1
      matrix:
        version:
        - v1.23.5+k0s.0
        - v1.22.8+k0s.0
        - v1.21.11+k0s.0
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go

      - uses: actions/cache@v2
        name: Go modules cache
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: checkout k0s release
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          git checkout 46d193ba35c3f9572c8b856b84cde1ef6acc0ac2 -- docs/requirements_release.txt
          pip install -r docs/requirements_release.txt
          git rm -f docs/requirements_release.txt
          pip install git+https://${{ secrets.GH_TOKEN }}@github.com/lensapp/mkdocs-material-insiders.git
          go install github.com/k0sproject/version/cmd/k0s_sort@v0.2.2

      - name: Generate docs
        run: |
          make -C docs cli TARGET_VERSION='${{ matrix.version }}'
          git checkout '${{ matrix.version }}'
          mkdocs build --strict

      - name: git config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      # If this is a tag build, deploy as a new version
      - name: mike deploy new version
        run: |
          mike deploy --push '${{ matrix.version }}'

      - name: Update mike version aliases
        id: set_versions
        if: matrix.version == 'v1.23.5+k0s.0'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAGS=$(gh release list -L 1000 -R k0sproject/k0s | grep "+k0s." | grep -v Draft | cut -f 1 | k0s_sort)
          LATEST=$(echo "${TAGS}" | tail -1)
          STABLE=$(echo "${TAGS}" | grep -v -- "-" | tail -1)
          mike alias -u head main
          mike alias -u "${LATEST}" latest
          mike alias -u "${STABLE}" stable
          mike set-default --push stable
          echo ::set-output name=LATEST::${LATEST}
          echo ::set-output name=STABLE::${STABLE}

      # Ensures the current branch is gh-pages,
      # Creates / updates the "stable" and "latest" plain text files with the corresponding versions
      # Commits if the files were changed
      # Finally pushes if there are unpushed commits
      - name: Create version files
        if: matrix.version == 'v1.23.5+k0s.0'
        run: |
          LATEST=${{ steps.set_versions.outputs.LATEST }}
          STABLE=${{ steps.set_versions.outputs.STABLE }}
          git checkout gh-pages
          echo "${STABLE}" > stable.txt
          git add stable.txt && git update-index --refresh
          git diff-index --quiet HEAD -- || git commit -m "Set stable to ${STABLE}"
          echo "${LATEST}" > latest.txt
          git add latest.txt && git update-index --refresh
          git diff-index --quiet HEAD -- || git commit -m "Set latest to ${LATEST}"
          git push origin gh-pages
