name: Manually publish docs via GitHub Pages
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g."v1.22.4+k0s.0")'
        required: true

env:
  PYTHON_VERSION: 3.x
  TARGET_VERSION: ${{ github.event.inputs.version }}

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout k0s ${{ github.event.inputs.version }}
        uses: actions/checkout@v2
        with:
          ref: "${{ github.event.inputs.version }}"
          fetch-depth: 0

      - name: Checkout k0s main
        uses: actions/checkout@v2
        with:
          ref: "main"
          path: "main"
          fetch-depth: 0

      - name: Copy files from main to ${{ github.event.inputs.version }}
        run: |
          cp -p main/docs/Makefile docs/Makefile
          cp -p main/mkdocs.yml mkdocs.yml
          rm -rf main

      - name: Prepare docs environment
        run: .github/workflows/prepare-docs-env.sh

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Generate docs
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: .github/workflows/generate-docs.sh

      - name: git config
        run: |

      - name: mike deploy ${{ github.event.inputs.version }}
        run: |
          mike deploy --push --force ${{ github.event.inputs.version }}
