on:
  push:
    branches:
      - win-wsl

jobs:
  wsl:
    runs-on: windows-2022

    steps:
      - name: Install Ubuntu
        run: |
          wsl --update
          wsl --set-default-version 2
          wsl --install Ubuntu

      - name: Start k0s controller
        run: |
          wsl sh -c 'curl --proto =https --tlsv1.2 -sSf https://get.k0s.sh | sh'
          wsl sh -c 'mkdir /etc/k0s && echo spec: \{storage: \{type: kine\}\} >/etc/k0s/k0s.yaml'
          wsl k0s install controller --debug --disable-components metrics-server
          wsl k0s start

      - name: Prepare kubeconfig
        run: |
          $ErrorActionPreference = "Stop"

          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
          Install-Module -Name powershell-yaml -Scope CurrentUser

          $attempt = 0
          while ($true) {
              try {
                  Write-Host "Attempt $($attempt + 1) ..."
                  $kubeconfig = & wsl k0s kubeconfig admin | ConvertFrom-Yaml
                  foreach ($cluster in $kubeconfig.clusters) {
                    $cluster.cluster.server = "https://localhost:6443"
                  }
                  $kubeconfig | ConvertTo-Yaml | Out-File -FilePath kubeconfig -Encoding utf8
              }
              catch {
                  $attempt++
                  Write-Warning "Failed to get kubeconfig in attempt ${attempt}: $_.Exception.Message"
                  if ($attempt -ge 5) {
                    Write-Error "Aborting!"
                    exit 1
                  }

                  Write-Warning "Retrying in 5 seconds..."
                  Start-Sleep -Seconds 5
              }

              Write-Host "Kubeconfig written to file"
              break
          }

          "KUBECONFIG=" + (Resolve-Path "kubeconfig").Path | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8

      - name: Try to connect
        run: |
          Write-Host $env:KUBECONFIG
          & kubectl auth whoami

      - name: k0s worker
        run: |
          $ErrorActionPreference = "Stop"
          $k0sVersion = (Invoke-WebRequest -URI https://docs.k0sproject.io/latest.txt).Content.Trim()
          $k0sURL = "https://github.com/k0sproject/k0s/releases/download/$k0sVersion/k0s-${k0sVersion}-amd64.exe"
          Invoke-WebRequest -URI $k0sURL -OutFile k0s.exe
          & .\k0s --help
